### PR TITLE
Updated API-Checker from v2.6.0 to v2.6.1.

### PR DESCRIPTION
**Pull request by wdschei**

### CODE REVIEW

**Comment by wdschei** [comment]
The failure is expected due to an assumption during the writing of this [test](https://github.com/rackerlabs/repose/blob/REP-6628_PrepReleaseV2-6-1/repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/filters/apivalidator/multitenant/headerAllAtMethodTenantExplicit.wadl.xml#L14). The casing issue has been corrected in the [REP-6658_ParamCaseFix](https://github.com/rackerlabs/repose/blob/REP-6658_ParamCaseFix/repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/filters/apivalidator/multitenant/headerAllAtMethodTenantExplicit.wadl.xml) branch which has been rebased off of this one.

**Comment by wdschei** [comment]
It would probably be a good idea to go ahead and bring the [REP-6448_MultiTenantRBAC](https://github.com/rackerlabs/repose/pull/1870) and [REP-6658_ParamCaseFix](https://github.com/rackerlabs/repose/pull/1871) branches into this one and let the full integrated test suite of the new API-Checker feature run sooner rather than later.

**Comment by dmnjohns** [comment]
Dependencies files should be updated.

**Comment by dmnjohns** [comment]
Retest this please

**Comment by dmnjohns** [comment]
Expected tests passed on the merged branches (which were based off of this branch), and all tests passed locally, so I'm going to go ahead and merge this.

**Pull request merged**
