### PR TITLE
REP-2941 Use the Java environment variable rather than checking the path

### PR DESCRIPTION
**Pull request by dmnjohns**
Manually tested, and this seems to work just fine.

### CODE REVIEW

**Comment by dmnjohns** [comment]
The comments need to be updated.

**Comment by dkowis** [comment]
My bad, I thought we didn't want to use environment vars :|

**Comment by dmnjohns** [comment]
How come? It seems reasonable since that's what we're using to launch Repose, but maybe there's something I don't know here.

**Comment by dkowis** [comment]
No this is fine. I didn't even know we had an `/etc/[sysconfig|default]/repose` that we were using to set the java location explicitly.

**Comment by dmnjohns** [comment]
retest this please

**Comment by dmnjohns** [comment]
retest this please

**Comment by adrianjgeorge** [comment]
retest this please

**Comment by dmnjohns** [comment]
So there was a comment about using JAVA_HOME, although that would be a change potentially requiring users to update their environment after upgrading Repose.

Otherwise, is this ready to be pulled in?

**Comment by adrianjgeorge** [comment]
It mostly ready, i'm just waiting on confirmation from @jennyvo that she's manually tested it.

**Comment by jennyvo** [comment]
QE manually tested.

**Pull request merged**
