### PR TITLE
REP-5309 Performance Test Inventory Refactor

### PR DESCRIPTION
**Pull request by Mario-Lopez**
- Refactored the inventory-per-test concept to vars_file-per-test
- Changed name of load balancer to make more sense
- Minor syntax change to "when"-type blocks due to upgrade to Ansible 2.3.0.0
- Updated shell/tar task to use new "archive" task in Ansible 2.3.0.0
- Updated README to reflect the changes

Also updated interim setup instructions in old perf repo:
https://github.com/rackerlabs/repose-perf-infrastructure/pull/34

Ansible playbooks now requires Ansible 2.3.0.0 minimum.

### CODE REVIEW

**Comment by dmnjohns** [comment]
I'll merge it once the tests pass (although given the change, I only really care if the doc building task passes).

**Comment by dmnjohns** [comment]
That's odd. A functional test failed. It looks like `MetricsEnableDisableTest` was the culprit.

**Comment by Mario-Lopez** [comment]
I wrote a story:
https://repose.atlassian.net/browse/REP-5409

**Comment by dmnjohns** [comment]
Legit. Since it passes tests prior to your change, and your change only touched docs (which built), I'm calling this good.

**Pull request merged**
