### PR TITLE
REP-2439 No 500's when username and password are blank when using Basic Auth.

### PR DESCRIPTION
**Pull request by adrianjgeorge**

### CODE REVIEW

**Comment by dmnjohns** [comment]
retest this please

**Comment by wdschei** [comment]
Looks good. Waiting on tests to pass.

**Comment by adrianjgeorge** [comment]
i'm an idiot, i didn't stop it from continuing from trying to go ahead and hit identity anyway. change inbound

**Comment by wdschei** [comment]
Retest this please.

**Pull request merged**
