### PR TITLE
REP-4555 Fix header name casing being modified.

### PR DESCRIPTION
**Pull request by wdschei**

### CODE REVIEW

**Comment by adrianjgeorge** [comment]
Could you add a test hat includes a header from the excluded set, and make sure it does the right thing. Otherwise looks good.

**Comment by wdschei** [comment]
Test added.

**Comment by adrianjgeorge** [comment]
The tests that are failing ar looking for the header names with a lower case, so they need fixing

**Comment by wdschei** [comment]
That was a little more painful than anticipated to fix correctly. The failing tests are now Case Insensitive.

**Comment by adrianjgeorge** [comment]
retest this please

**Pull request merged**
