### PR TITLE
DO NOT MERGE YET - REP-2188 Spike to update to new wrappers

### PR DESCRIPTION
**Pull request by wdschei**

### CODE REVIEW

**Comment by wdschei** [comment]
Retest this please.

**Comment by wdschei** [comment]
Retest this please.

**Comment by wdschei** [comment]
Retest this please.

**Comment by wdschei** [comment]
Retest this please.

**Comment by wdschei** [comment]
Retest this please.

**Comment by wdschei** [comment]
Retest this please.

**Comment by wdschei** [comment]
Retest this please.

**Comment by wdschei** [comment]
Retest this please.

**Comment by wdschei** [comment]
Retest this please.

**Comment by wdschei** [comment]
Retest this please.

**Comment by wdschei** [comment]
Retest this please.

**Comment by wdschei** [comment]
Retest this please.

**Comment by wdschei** [comment]
Retest this please.

**Comment by wdschei** [comment]
Retest this please.

**Comment by wdschei** [comment]
Retest this please.

**Comment by wdschei** [comment]
Retest this please.

**Comment by wdschei** [comment]
Retest this please.

**Comment by wdschei** [comment]
Retest this please.

**Comment by wdschei** [comment]
Retest this please.

**Comment by wdschei** [comment]
Retest this please.

**Comment by wdschei** [comment]
Retest this please.

**Comment by adrianjgeorge** [comment]
this has had it's purpose, do we want to close the pr, but leave the branch?

**Comment by wdschei** [comment]
I was going to leave it open until I finished tinkering with it. I may have found another deep dive fix that will make it truly viable. I am going to continue rebasing it to keep it up to date.

**Comment by adrianjgeorge** [comment]
fair enough

**Comment by Mario-Lopez** [comment]
Retest this please

**Comment by wdschei** [comment]
This was basically renamed to `repose-8-staging ` so this branch is no longer needed.

**Pull request closed without merging**
