### PR TITLE
REP-3260 Forwarded Proto filter updated to use new wrappers

### PR DESCRIPTION
**Pull request by Mario-Lopez**
Updated usage of old wrapper to new wrapper.

### CODE REVIEW

**Comment by Mario-Lopez** [comment]
There was an unexpected test failure.  I will look.

**Comment by Mario-Lopez** [comment]
The unexpected test failure is for a test that only exists on master and is unrelated to the changes introduced in this pull request.  I'm not sure why it would be failing now.

**Comment by Mario-Lopez** [comment]
retest this please

**Comment by adrianjgeorge** [comment]
hooray back to the expected 24

**Pull request merged**
