### PR TITLE
Runtime improvements for config loading/reloading tests

### PR DESCRIPTION
**Pull request by pglass**
This removes or replaces some hardcoded sleeps in the `TransitionBadToGoodConfigsTest` and `TransitionGoodToBadConfigsTest`. 

I recorded the runtimes before/after these changes in the commit messages, so please look through those. Adding up the differences for the modified tests, this saved 2 minutes out of about 19 minutes on my laptop.

- Before: 18m48s
- After: 16m42s

### CODE REVIEW

**Comment by pglass** [comment]
Not a worthwhile difference on Jenkins: https://jenkins.openrepose.org/job/repose-gradle-pull_request-core/70/testReport/features.core.configloadingandreloading/history/ and it actually took a bit longer than usual for these tests. I'm wondering if the waits take longer than the sleeps they replaced.

**Comment by adrianjgeorge** [comment]
Could just be noisy neighbor or the particular slave you ended up on.

**Comment by adrianjgeorge** [comment]
Retest this please

**Comment by pglass** [comment]
Whoo, so build 74 is the fastest it's ever been: https://jenkins.openrepose.org/job/repose-gradle-pull_request-core/74/testReport/features.core.configloadingandreloading/history/

**Comment by adrianjgeorge** [comment]
Seems like there are improvements then, and it was just a cloud resource problem on the first run.

**Pull request merged**
