### PR TITLE
REP-4323 Updated the API-Checker version to 2.0.1.

### PR DESCRIPTION
**Pull request by wdschei**

### CODE REVIEW

**Comment by wdschei** [comment]
Retest this please.

**Comment by adrianjgeorge** [comment]
retest this please

**Comment by adrianjgeorge** [comment]
test this please

**Comment by adrianjgeorge** [comment]
test this please

**Comment by adrianjgeorge** [comment]
test this please

**Comment by wdschei** [comment]
Since the Jenkins to GitHub hooks are currently buggered, this is the build for the f60a46a commit:

- https://jenkins.openrepose.org/job/repose-gradle-pull_request/589/

**Pull request merged**
