### PR TITLE
Gradle functional tests

### PR DESCRIPTION
**Pull request by adrianjgeorge**
Now with possibly passing functional tests. At a minimum the smoke test works.

### CODE REVIEW

**Comment by adrianjgeorge** [comment]
retest this please

**Comment by adrianjgeorge** [comment]
Retest this please

**Comment by Mario-Lopez** [comment]
retest this please

**Comment by Mario-Lopez** [comment]
retest this please

**Comment by Mario-Lopez** [comment]
retest this please

**Comment by adrianjgeorge** [comment]
retest this please

**Comment by adrianjgeorge** [comment]
retest this please

**Comment by adrianjgeorge** [comment]
Retest this please

**Pull request merged**
