### PR TITLE
Add Test herp derp with response message config

### PR DESCRIPTION
**Pull request by jennyvo**

### CODE REVIEW

**Comment by wdschei** [comment]
Test this please.

**Comment by wdschei** [comment]
Retest this please.

**Comment by dimtruck** [comment]
Retest this please.

**Comment by dimtruck** [comment]
@wdschei, @adrianjgeorge @dmnjohns can you guys trigger this PR?  This is for REP-2304

**Comment by wdschei** [comment]
Retest this please.

**Comment by adrianjgeorge** [comment]
This has been split itno two seperate bugs and branches.

**Pull request closed without merging**
