### PR TITLE
REP-3743 Adding configurable role to the verify-try-it-now command

### PR DESCRIPTION
**Pull request by dmnjohns**
We will need to release from this branch after code and QE review are completed.

### CODE REVIEW

**Comment by dmnjohns** [comment]
The 3 failing tests here are expected. All 3 are caused by the pull request changes being merged to master before tests are run, but this won't be an issue when we release from this branch.

**Comment by Mario-Lopez** [comment]
Changes look pretty straightforward.  No QE tests, though?

**Comment by jennyvo** [comment]
I did verify from command line, but yes no test add to current functional tests.

**Comment by jennyvo** [comment]
I think I can try to add functional test...

**Comment by Mario-Lopez** [comment]
There were 8 expected failures and 1 new one I haven't seen before.  Does anyone know if LockedConfigurationUpdaterTest is a flakey test?  It is a multi-threaded test. :-/

Perhaps we should just re-run the build.

https://jenkins.openrepose.org/job/repose-pull_requests/org.openrepose$configuration/1133/testReport/junit/org.openrepose.commons.config.manager/LockedConfigurationUpdaterTest$WhenLockingOperations/shouldNotLockWhenUsingSharedKeys/

**Comment by jennyvo** [comment]
maybe because 1 of check format failed...just update and verified those tests passed locally

**Pull request merged**
