### PR TITLE
REP-5261 Translation Entity Expansion testing

### PR DESCRIPTION
**Pull request by wdschei**

### CODE REVIEW

**Comment by adrianjgeorge** [comment]
i just merged this, but where was the doc update we talked about?

**Comment by dmnjohns** [comment]
I would note that we have not yet migrated the Translation filter documentation to the new docs. I suppose that could have been part of this story? Otherwise, I would expect a documentation update to the Wiki.

**Comment by adrianjgeorge** [comment]
Ahh, you are probably correct. Fair enough.

**Comment by wdschei** [comment]
Yep. I updated the [Preventing XML Bomb](https://repose.atlassian.net/wiki/spaces/REPOSE/pages/26312808/Prevent+XML+bomb+attacks) page on the Wiki.

**Pull request merged**
