### PR TITLE
REP-3577 - Configure request headers in HTTP connection pools

### PR DESCRIPTION
**Pull request by Mario-Lopez**
I updated the HTTP Connection Pool configuration to allow a list of headers to be configured for a connection pool.  I also updated the HttpConnectionPoolProvider to set the configured headers as default headers in the HttpClient.

I added a functional test (with the v2v2 filter configured to use a connection pool with a configured header) to verify that the call to identity contained the configured header and that the origin service (which used the default connection pool) did not receive said header.

### CODE REVIEW

**Comment by wdschei** [comment]
Looks good. Tests pass. I will wait and see what @jennyvo adds and take another look.

**Comment by adrianjgeorge** [comment]
I like the functional test, but why no unit test?

**Comment by Mario-Lopez** [comment]
I wasn't sure HttpClient was going to do what I wanted, so I wrote the functional test to verify stuff.  At that point it felt weird to write a unit test to confirm that I populated a parameter, but I totally can if you want.

**Comment by adrianjgeorge** [comment]
If it's realtively easy do it, otherwise don't worry about it.

**Comment by Mario-Lopez** [comment]
No problem at all.  Unit tests added.

**Pull request merged**
