### PR TITLE
Clearing TechDebt for the "Catch Exception instead of Throwable." rule in SonarQube (squid:S1181).

### PR DESCRIPTION
**Pull request by wdschei**

### CODE REVIEW

**Comment by wdschei** [comment]
Retest this please.

**Comment by wdschei** [comment]
Retest this please.

**Comment by adrianjgeorge** [comment]
These shouldn't be suppressed, in fact they should have a timebomb, API validator should not be throwing a generic throwable that's a terrible api.

**Comment by wdschei** [comment]
So remove the original `PMD.AvoidCatchingThrowable` and add a timebomb?

**Pull request merged**
