### PR TITLE
Rep 1527 - Forwarded Proto Header Filter

### PR DESCRIPTION
**Pull request by InblEric**
From the acceptance criteria:

X-FORWARDED-PROTO: http 
X-FORWARDED-PROTO: https

Looks like http actually comes in as HTTP/1.1 but I don't think this should be a problem as long as whoever uses the filter knows what they're looking for. I assume https would come in as HTTPS but I'm not entirely sure.

### CODE REVIEW

**Comment by wdschei** [comment]
Retest this please.

**Comment by adrianjgeorge** [comment]
why would their snapshots be in central, but not the actual releases? that doesn't seem right

**Comment by adrianjgeorge** [comment]
there's no config to speak of, so lets not do the factory and all that other crap. Justa plain simple filter should do the job. also we should check the output and make sure it's consistent with nginx?

**Comment by dkowis** [comment]
@adrianjgeorge this is why: https://github.com/rackerlabs/repose/pull/1124#discussion_r18177949 They're not publishing releases there yet.

**Comment by dmnjohns** [comment]
Closing this. Refer to #1215

**Pull request closed without merging**
