### PR TITLE
Rate Limiting Against Query Value With Capture Groups

### PR DESCRIPTION
**Pull request by dmnjohns**
Sorry about the reformatting. It had to happen. Had to! (Also, I wasn't sure I was going to submit a pull request when I was working on this, so things may be a bit messy).

### CODE REVIEW

**Comment by dkowis** [comment]
retest this please

**Comment by dkowis** [comment]
retest this please

**Comment by dkowis** [comment]
retest this please

**Comment by dkowis** [comment]
retest this please

**Comment by dmnjohns** [comment]
retest this please

**Comment by dkowis** [comment]
Oh noes it's not mergable again. We really should merge this thing that someone somewhere maybe wants?

**Comment by dkowis** [comment]
although, if we wait a few more months, we will have had it open for a year!

**Comment by adrianjgeorge** [comment]
yeah, it's waiting on qe, @dimtruck has said he'd test it, but never gets there. we should add a story for it so he actually does it

**Comment by jennyvo** [comment]
I can create test for this and will log time if it has a story or log as ninja task

**Comment by dmnjohns** [comment]
I'm going to go ahead and close this PR. It doesn't look like it's going to get merged, and I'm okay with that. I'll leave the branch for now in case it's relevant in the future.

**Pull request closed without merging**
