### PR TITLE
Updated the API-Checker version to 1.1.4.

### PR DESCRIPTION
**Pull request by wdschei**

### CODE REVIEW

**Comment by adrianjgeorge** [comment]
We also wanted to turn the new option on  by default

**Comment by wdschei** [comment]
Yes, we did. Updated.

**Comment by adrianjgeorge** [comment]
Of course now it needs a test to prove that the feature is on and working.

**Comment by wdschei** [comment]
We aren't going to rely on the API-Checker tests for this?

**Comment by adrianjgeorge** [comment]
We need a test to prove that we are defaulting it to on. I'm fine with a unit test.

**Comment by adrianjgeorge** [comment]
You made a prod code change that had no test requiring it.

**Comment by wdschei** [comment]
Unfortunately The API-Validator filter uses the old pattern which precludes adding easy unit tests. Also since there were other functional tests dealing with required headers, I was able to easily add a new set of tests around them.

**Comment by adrianjgeorge** [comment]
That works, hopefully it goes green and i'll merge it.

**Pull request merged**
