### PR TITLE
DO NOT MERGE: REP-1553 - 6.2.2.0 release

### PR DESCRIPTION
**Pull request by wdschei**
The following have been cherry-picked into 6.2.1.2:
* REP-729 (492d553fbe95575c24fcf861a627f94eee23070c^..1f92583760c77b7bc66932d70b66c5696a5ef9a4)
* REP-1528 (c79549e78c44a9c854b39a8b647589c1c5e26330^..309fc861a8bc9331c2521cb244c52644c1c3003d)
* REP-1540 (f4517c5ae8811b8ea08344587eb4978586cd97fb^..2d6078a7ff5a6f1f83d9e1f0c220963301928fcf)
* REP-1527 (21c7855fa33160f790e88f3f751dffc890b048cc^..5a8becb9d025f2675ee3912d9dd940ae1bb0a471)
* REP-1560 (58b0f16d4774777c2da3d3e4b873c448d50ecf7e^..a226dd8fe26de32486b6f86523ac1f57eb2a6bd1)
* REP-1595 (418a53731e33ba1e032745f8fb538a2740f9a000^..e688064624e6873311eef003811f26717047ac99)

I also brought in the time bomb update to the DistDatastoreServiceContainerTest
* 83bf07bd008d6c3453324900a1716fd28f154e0f
* 5b20c7ed0ae4c7b4a9b681fa4ce9c8a20b4ad257
* 970219f55810411816b2cb2336987399f6f554c2

Fixed some merge issues with the cherry-pick and assumptions made in master.
Commented out sections of AkkaServiceClientImplTest that expected the new SLF4J 2.x framework since this is not compatible with the earlier version provided in the backported release.

### CODE REVIEW

**Comment by tylerroyal** [comment]
retest this please

**Comment by wdschei** [comment]
Retest this please.

**Comment by wdschei** [comment]
This fails because the delegable stuff.

**Comment by adrianjgeorge** [comment]
retest this please

**Comment by adrianjgeorge** [comment]
retest this please

**Comment by adrianjgeorge** [comment]
retest this please

**Pull request merged**
