### PR TITLE
Updated the WAR pom to include the missing Log4J 2.x jars and to exclude the old commons-logging.

### PR DESCRIPTION
**Pull request by wdschei**
Also put the Spring dependencies in the same order as the Valve POM to make for easier comparisons.

### CODE REVIEW

**Comment by adrianjgeorge** [comment]
who was doing the exclusion or changing in scope?

**Comment by wdschei** [comment]
These were not being excluded, they were just never being included. Since these are not needed at compile time they are not pulled in as dependencies. Therefore they have to be explicitly included like they were in the Valve POM. This is what the WAR POM change is.

This needs a test to confirm that all currently released 7.x versions fail and this branch forward pass. I just don't know what that would look like in our WAR testing framework. I will get with QE to figure this out.

**Comment by dkowis** [comment]
I might be wrong, but doesn't the container provide the logging infrastructure in general with WAR file deployments?

**Comment by wdschei** [comment]
The containers may supposed to be, but the internal Glassfish deployments were failing until they were added to the WAR.

**Comment by adrianjgeorge** [comment]
the container is under no obligation to provide any sort of logging infrastructure to the app being run. It may have logging of its own and it's logs might include the apps depending on if they are fundamentally the same system, but it's not a guarantee. We need to be sure we provide the concrete implementations so that our logging works in either case.

**Pull request merged**
