### PR TITLE
REP-2836 Don't Return Guava Types From Core API

### PR DESCRIPTION
**Pull request by dmnjohns**

### CODE REVIEW

**Comment by wdschei** [comment]
Everything that is here, looks good. The only things in question are the one test failure:

- https://jenkins.openrepose.org/job/repose-gradle-pull_request/299/testReport/junit/org.openrepose.commons.config.manager/LockedConfigurationUpdaterTest$WhenLockingOperations/shouldNotLockWhenUsingSharedKeys/

and the possible removal of the the Guava dependency from core:

- https://github.com/rackerlabs/repose/blob/REP-2836/repose-aggregator/core/repose-core/build.gradle#L44

by getting rid of the use of these static one-liners:

- https://github.com/google/guava/blob/master/guava/src/com/google/common/base/Objects.java#L56-L58
- https://github.com/google/guava/blob/master/guava/src/com/google/common/base/Objects.java#L80-L82
-https://github.com/google/guava/blob/master/guava/src/com/google/common/base/Throwables.java#L251-L257

in these locations:

- https://github.com/rackerlabs/repose/blob/REP-2836/repose-aggregator/core/repose-core/src/main/java/org/openrepose/core/services/reporting/destinations/impl/DestinationInfoLogic.java#L157
- https://github.com/rackerlabs/repose/blob/REP-2836/repose-aggregator/core/repose-core/src/main/java/org/openrepose/core/services/reporting/destinations/impl/DestinationInfoLogic.java#L165
- https://github.com/rackerlabs/repose/blob/REP-2836/repose-aggregator/core/repose-core/src/main/java/org/openrepose/core/services/reporting/destinations/impl/DestinationInfoStore.java#L114-L119
- https://github.com/rackerlabs/repose/blob/REP-2836/repose-aggregator/core/repose-core/src/main/java/org/openrepose/core/services/reporting/destinations/impl/DestinationInfoStore.java#L127
- https://github.com/rackerlabs/repose/blob/REP-2836/repose-aggregator/core/repose-core/src/main/java/org/openrepose/nodeservice/httpcomponent/RequestProxyServiceImpl.java#L174

All that said, we would still be bringing in Guava for the Cache in `akka-http-client-service`:

- https://github.com/rackerlabs/repose/blob/REP-2836/repose-aggregator/components/services/akka-http-client-service/akka-http-client-service-impl/src/main/java/org/openrepose/core/services/serviceclient/akka/impl/AkkaServiceClientImpl.java#L29-L30

**Comment by dmnjohns** [comment]
retest this please

**Comment by dmnjohns** [comment]
So I have no idea why that one test randomly failed earlier, but it's passing now...

**Comment by wdschei** [comment]
Sounds good and looks good. Waiting on QE approval and I will merge it.

I figure the total removal of the Guava dependency from `core` would be out of scope for this particular story, so it would need a new story and accompanying PR anyway.

**Comment by dmnjohns** [comment]
I'm in the same boat. I was going to ask @adrianjgeorge about it again this morning, but since it's totally something we can break off, I think I prefer doing that.

**Comment by Mario-Lopez** [comment]
image

**Pull request merged**
