### PR TITLE
REP-3960 - Update README

### PR DESCRIPTION
**Pull request by Mario-Lopez**
I updated the README.  I removed some stuff I thought was better explained in the docs and added a bunch of links.

### CODE REVIEW

**Comment by Mario-Lopez** [comment]
Link to look at the rendered Markdown:
https://github.com/rackerlabs/repose/tree/REP-3960-Update-README

**Comment by adrianjgeorge** [comment]
huh, this didn't go through the pr builder, that's curious that it knew better

**Comment by Mario-Lopez** [comment]
I was just noticing the same thing.

**Comment by adrianjgeorge** [comment]
looks legit.

**Pull request merged**
