### PR TITLE
DO NOT MERGE: REP-5588 Removing the global kill before startup for parallel functional tests.

### PR DESCRIPTION
**Pull request by wdschei**

### CODE REVIEW

**Comment by dmnjohns** [comment]
retest this please

I updated Jenkins, and even though this is not to be merged yet, might as well run things.

**Comment by adrianjgeorge** [comment]
Wow, that's a lot of failures

**Comment by Mario-Lopez** [comment]
At first I was pleasantly surprised to see only 154 failures. Then I noticed it only ran 6,879 tests instead of the 15,564 it should have ran (which includes both functional and unit tests).

**Comment by adrianjgeorge** [comment]
Maybe it's just bad reporting?

**Comment by adrianjgeorge** [comment]
retest this please

**Comment by wdschei** [comment]
This was run in the full parallel mode (e.g. `-PintegrationTestMaxParallelForks=4`) here:
> https://jenkins.openrepose.org/job/repose-gradle-pull_request/1446/

**Pull request closed without merging**
