### PR TITLE
Rep 1572 Include header that differentiates default project ID in keystone v3

### PR DESCRIPTION
**Pull request by JoelRizner**

### CODE REVIEW

**Comment by wdschei** [comment]
You need to update the example config show the use of the new element and it's attributes.

**Comment by Mario-Lopez** [comment]
Don't forget to update the example config in the artifact's directory, too.

**Comment by JoelRizner** [comment]
is that the one in artifacts/filter-bundle/src/config/filters?

**Comment by wdschei** [comment]
Yep. That is the second one.

**Pull request merged**
