### PR TITLE
REP-5411 Modify Gatling Output Name

### PR DESCRIPTION
**Pull request by dmnjohns**

### CODE REVIEW

**Comment by dmnjohns** [comment]
So as @Mario-Lopez pointed out yesterday, this does not give us separation between the languages used by the scripting filter performance test.

If we want to keep the current test structure, I suggest we achieve that separation by including the language in the scenario name. I can add that to this PR if that is the way we want to go.

**Comment by dmnjohns** [comment]
Since the scripting language information is encoded in Ansible itself (as a test variable and directory) I had to make the change in Ansible (and thus, in the Gatling output name) rather tahn in the HTTP request name.

Since changing the `gatling.test.name` would have a number of complications, I just added a `gatling.test.id` that the scripting filter tests will use (although others could as well, if other tests end up in a similar situation). Then, the Gatling output name is set to the id if present, otherwise it is set to the name.

**Comment by dmnjohns** [comment]
Retest this please.

**Comment by dmnjohns** [comment]
I'm rerunning the tests that failed, but both passed locally.

Considering that my changes were exclusively to Ansible stuff, and Ansible isn't being run as part of the tests yet, I would say that this is probably good to go at any time.

**Comment by wdschei** [comment]
If they pass locally, then I concur.

**Pull request merged**
