### PR TITLE
REP-4404 Merge v7.3.7.0 into master.

### PR DESCRIPTION
**Pull request by wdschei**

### CODE REVIEW

**Comment by wdschei** [comment]
Jenkins build: https://jenkins-proto.openrepose.org/job/repose-gradle-pull_request/633/

**Comment by adrianjgeorge** [comment]
missed a commit, 06480c3f880ecb9710a2dbe576e3701a8995d05d

**Comment by adrianjgeorge** [comment]
whelp, it says it'll merge clean and the tests pass, i guess there's nothing to do but merge it after you get on that other commit, and then take a look to make sure there isn't anything lingering around

**Comment by wdschei** [comment]
The missing commit was added and the Jenkins run is:

 - https://jenkins-proto.openrepose.org/job/repose-gradle-pull_request/644/

**Pull request merged**
