### PR TITLE
CAN MERGE FOR THE WIN: REP-1158 Core Spring

### PR DESCRIPTION
**Pull request by dkowis**
This is only opened for review ease. It will fail the jenkins builds.

SHIP IT

### CODE REVIEW

**Comment by dkowis** [comment]
retest this please

**Comment by dkowis** [comment]
retest this please

**Comment by dkowis** [comment]
retest this please

**Comment by dkowis** [comment]
For reference, here's the etherpad we're using to track who's working on what (Although it's done now) https://etherpad.wikimedia.org/p/SpringWork

**Comment by wdschei** [comment]
Retest this please.

**Comment by dkowis** [comment]
Yeah those tests are likely flakey. With the JMX ones we probably just need to have the tests poll for a period of time, rather than waiting for a point, and then asserting the thing.

The self-configure thing, for node services, I think at this stage, we're going to have to set a volatile boolean in the service itself, that we set when shutting down.... Or perhaps better modify the healthcheckserviceproxy so that you can say, "I'm healthy no matter what after this point." And it'll ignore further reports.... I dunno.

**Comment by wdschei** [comment]
Since there are no other jobs running on Jenkins this morning, I'm just going to try and flush out some more flaky tests.

**Comment by wdschei** [comment]
Retest this please.

**Comment by wdschei** [comment]
Retest this please.

**Comment by wdschei** [comment]
Retest this please.

**Comment by dkowis** [comment]
That classloader test failed due to a lack of disk space: 

2015-01-10 00:30:01,176 7038 [Event Kernel Thread] ERROR org.openrepose.core.services.deploy.ArtifactManager - Failure in loading artifact, "/var/lib/jenkins/workspace/repose-pull_requests/repose-aggregator/functional-tests/spock-functional-test/target/repose_home/artifacts/classloader-bundle-four-3.0.ear". Reason: Unable to fully extract file

**Comment by dkowis** [comment]
Well, no it wasn't out of disk space, unless somehow that disk space usage got cleaned up. They're all still with plenty of space...

**Comment by dkowis** [comment]
retest this please

**Comment by dkowis** [comment]
retest this please

**Comment by dkowis** [comment]
retest this please

**Comment by dkowis** [comment]
retest this please

**Comment by dkowis** [comment]
retest this please

**Comment by dkowis** [comment]
retest this please

**Comment by dkowis** [comment]
retest this please

**Comment by dkowis** [comment]
retest this please

**Comment by dkowis** [comment]
retest this please

**Comment by dkowis** [comment]
retest this please

**Comment by dkowis** [comment]
Queued up another pile of builds.

**Comment by tylerroyal** [comment]
Retest this please

Sent from my iPhone

On Jan 13, 2015, at 1:04 PM, repose-bot <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry, the tests failed.
Refer to this link for build results (access rights to CI server needed):
https://jenkins.openrepose.org//job/repose-pull_requests/1378/

Failed Tests: 2
com.rackspace.papi:repose-spock-tests<https://jenkins.openrepose.org/job/repose-pull_requests/1378/com.rackspace.papi%24repose-spock-tests/testReport>: 2

  *   features.core.powerfilter.ResponseCodeJMXTest.when sending requests, response code counters should be incremented<https://jenkins.openrepose.org/job/repose-pull_requests/1378/com.rackspace.papi%24repose-spock-tests/testReport/features.core.powerfilter/ResponseCodeJMXTest/when_sending_requests__response_code_counters_should_be_incremented/>
  *   features.core.powerfilter.ResponseCodeJMXTest.when responses have 2XX and 5XX status codes, should increment 2XX and 5XX mbeans<https://jenkins.openrepose.org/job/repose-pull_requests/1378/com.rackspace.papi%24repose-spock-tests/testReport/features.core.powerfilter/ResponseCodeJMXTest/when_responses_have_2XX_and_5XX_status_codes__should_increment_2XX_and_5XX_mbeans/>

Sorry, the tests failed.

**Comment by dkowis** [comment]
retest this please

**Comment by dkowis** [comment]
retest this please

**Comment by wdschei** [comment]
retest this please

**Comment by wdschei** [comment]
retest this please

**Comment by wdschei** [comment]
retest this please

**Comment by wdschei** [comment]
retest this please

**Comment by wdschei** [comment]
retest this please

**Comment by wdschei** [comment]
retest this please

**Comment by dkowis** [comment]
retest this please

**Comment by dkowis** [comment]
retest this please

**Comment by dkowis** [comment]
retest this please

**Comment by dkowis** [comment]
retest this please

**Comment by dkowis** [comment]
retest this please

**Comment by dkowis** [comment]
retest this please

**Comment by dkowis** [comment]
retest this please

**Comment by tylerroyal** [comment]
retest this please

**Comment by tylerroyal** [comment]
retest this please

**Comment by tylerroyal** [comment]
retest this please

**Comment by dkowis** [comment]
retest this please

**Comment by dkowis** [comment]
retest this please

**Comment by dkowis** [comment]
retest this please

**Comment by dkowis** [comment]
retest this please

**Comment by wdschei** [comment]
When the `scala-maven-plugin` is enabled in `<REPOSE>/repose-aggregator/services/service-client/impl/pom.xml` so the newly merged `<REPOSE>/repose-aggregator/services/service-client/impl/src/test/scala/org/openrepose/core/services/serviceclient/akka/impl/AkkaServiceClientImplTest.scala` test can be compiled and executed the following error is received:

```
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.1.6:compile (scala-compile-first) on project service-client-akka:
        Execution scala-compile-first of goal net.alchim31.maven:scala-maven-plugin:3.1.6:compile failed:
        An API incompatibility was encountered while executing net.alchim31.maven:scala-maven-plugin:3.1.6:compile:
        java.lang.ClassFormatError: Absent Code attribute in method that is not native or abstract in class file javax/ws/rs/core/MediaType
```

So the plugin was commented out in the last commit until we figure out what is going on.

**Comment by dkowis** [comment]
Didn't get to the Mbean server test yet. Got the build problem fixed, though.

**Comment by dkowis** [comment]
retest this please

**Comment by dkowis** [comment]
retest this please

**Comment by dkowis** [comment]
retest this please

**Comment by dkowis** [comment]
retest this please

**Comment by dkowis** [comment]
retest this please

**Comment by dkowis** [comment]
retest this please

**Comment by dkowis** [comment]
retest this please

**Comment by dkowis** [comment]
retest this please

**Comment by dkowis** [comment]
retest this please

**Comment by dkowis** [comment]
RETESTING ALL THE THINGS FOR GREAT JUSTICE!

**Pull request merged**
