### PR TITLE
if the tenant does not start with hybrid: then return a 403/404 if maske...

### PR DESCRIPTION
**Pull request by tylerroyal**
...d

### CODE REVIEW

**Comment by adrianjgeorge** [comment]
easy peasy, lets see it pass

**Comment by adrianjgeorge** [comment]
@jennyvo you going to write a masked version of the test as well?

**Comment by adrianjgeorge** [comment]
The pdf doesn't belong in the source code repository. If we want to keep it lets put it on the wiki somewhere.

**Comment by adrianjgeorge** [comment]
@tylerroyal looks good, rebase out the commit with the pdf and i'll merge it in

**Comment by tylerroyal** [comment]
Rebase accomplished.

**Pull request merged**
