### PR TITLE
REP-5347 Updating the attribute mapper library

### PR DESCRIPTION
**Pull request by dmnjohns**

### CODE REVIEW

**Comment by adrianjgeorge** [comment]
is the other one, the one that's going to update the json usage?

**Comment by dmnjohns** [comment]
Yup, that's @wdschei's https://repose.atlassian.net/browse/REP-5595.

**Comment by wdschei** [comment]
Yup, and then I can rebase it.

**Comment by dmnjohns** [comment]
retest this please

**Comment by adrianjgeorge** [comment]
looks liek we might get some last minute updates to this

**Comment by dmnjohns** [comment]
retest this please

**Comment by dmnjohns** [comment]
retest this please

**Pull request merged**
